baseURL = "https://runi.netlify.com"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Runi Goswami | Design Portfolio"
[[menu.main]]
URL = "about"
name = "Resume"
weight = 4
[[menu.main]]
URL = "writing"
name = "Writing"
weight = 3
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 2
[params]
address = "New York, NY"
author = "Runi Goswami"
copyright = ""
description = "Runicorn design"
email = "runigoswami@email.com"
google_analytics_id = ""
home = "Home"
logo = "images/Logo-Runi-vector.svg"
phone = "5713458928"
theme_color = "#4323C0"
[params.contact]
enable = false
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://www.linkedin.com/in/runigoswami/"
icon = "ti-linkedin"
url = "https://www.linkedin.com/in/runigoswami/"
[[params.social]]
URL = "https://medium.com/@loonyruni"
icon = "ti-medium"
url = "https://medium.com/@loonyruni"
