# default configuration
baseURL = "https://runi.netlify.com"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Runi Goswami | Design Portfolio"

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"


# menu
[[menu.main]]
URL = "about"
name = "Resume"
weight = 4

#[[menu.main]]
#URL = "https://medium.com/@loonyruni"
#name = "Writing"
#url = "https://medium.com/@loonyruni"
#weight = 3

[[menu.main]]
URL = "writings"
name = "Writings"
weight = 3

[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 2

# default parameters
[params]
home = "Home"
logo = "images/Logo-Runi-vector.svg"
# theme color
theme_color = "#4323C0"
# contact info
phone = ""
email = "runigoswami@email.com"
address = ""
# meta description
author = "Runi Goswami"
description = "Runicorn design"
# google analytics
google_analytics_id = "" # Your ID
# copyright
copyright = ""


# contact
[params.contact]
enable = false
form_action = "#" # contact form works with : https://formspree.io

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# social site
[[params.social]]
URL = "https://www.linkedin.com/in/runigoswami/"
url = "https://www.linkedin.com/in/runigoswami/"
icon = "ti-facebook"
